import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import AOSInitializer from "@/pages/AOSInitializer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        <link rel="icon" href="/profile.jpg" />
        <meta property="og:image" content="/profile.jpg" />
      </Head>
      <body className={inter.className}>
      <AOSInitializer/>
        {children}</body>
    </html>
  );
}
